# USA
en-US:
  login: LOGIN
  name: English (USA)
  alarm.alarmList.emptyList.noFound: No alarms found for your criteria
  portal.main.header.showKeyboard: Show Keyboard

# France
fr-FR:
  login: CONNEXION
  name: Français (France)
  alarm.alarmList.emptyList.noFound: No alarms found for your criteria - FR
  portal.main.header.showKeyboard: Afficher le clavier