# USA
en-US:
  login: LOGIN
  name: English (USA)
  alarm.alarmList.emptyList.errorMessage: No alarms found for your criteria
  "portal.modal.list.userPreferences": User Preferences

# France
fr-FR:
  login: CONNEXION
  name: Français (France)
  alarm.alarmList.emptyList.errorMessage: No alarms found for your criteria - FR
  "portal.modal.list.userPreferences": portal.modal.list.userPreferences