USE [ReportManagement]
GO
DELETE FROM [dbo].[runheader]
GO
SET IDENTITY_INSERT [dbo].[runheader] ON
GO
INSERT [dbo].[runheader] ([id], [product_id], [batch_id], [run_id], [device_id], [machine_name], [recipe_procedure], [file_name], [start_date_time], [end_date_time], [user_name], [run_state], [preRun_comment], [postRun_comment], [step_id], [column_info], [packedBed_info], [sample_info], [buffer_info], [cip_start_time], [cip_end_time]) VALUES (1, N'p10', N'b10', N'recipe4sec220211129030358', N'CRS 50L', N'CRS 50L', N'Operation', N'recipe4sec2',DATEADD(ss, -4, GETUTCDATE()), GETUTCDATE(), N'Bio4cService', N'Completed', N'pre comments 10', N'post comments 10', N'', N'', N'', N'', N'', DATEADD(ss, -4, GETUTCDATE()), GETUTCDATE())
GO
INSERT [dbo].[runheader] ([id], [product_id], [batch_id], [run_id], [device_id], [machine_name], [recipe_procedure], [file_name], [start_date_time], [end_date_time], [user_name], [run_state], [preRun_comment], [postRun_comment], [step_id], [column_info], [packedBed_info], [sample_info], [buffer_info], [cip_start_time], [cip_end_time]) VALUES (2, N'p11', N'b11', N'recipe4sec220211129035111', N'CRS 50L', N'CRS 50L', N'Operation', N'recipe4sec2', DATEADD(ss, -10, GETUTCDATE()), DATEADD(ss, -6, GETUTCDATE()), N'Bio4cService', N'Aborted', N'pre comm', N'last c', N'', N'', N'', N'', N'', DATEADD(ss, -10, GETUTCDATE()), DATEADD(ss, -6, GETUTCDATE()))
GO
SET IDENTITY_INSERT [dbo].[runheader] OFF
GO
DELETE FROM [dbo].[report_template]
GO
SET IDENTITY_INSERT [dbo].[report_template] ON
GO
INSERT [dbo].[report_template] ([report_template_id], [report_template_name], [report_template_Json], [report_template_created_on], [report_template_created_by], [report_template_state], [report_template_status], [lastModifiedBy], [lastModifiedOn], [eSignatureCode], [approver], [signature_count], [template_type], [device_id], [is_default]) VALUES (1, N'testReportTemplate', N'[{"name":"Run Header","identifier":"runHeader","checked":true,"disabled":true},{"name":"Pre Run Data","identifier":"preRunData","checked":true},{"name":"Audit Trail","identifier":"auditTrail","checked":true},{"name":"Run Summary","identifier":"runSummary","checked":true},{"name":"Alarms","identifier":"alarms","checked":true,"value":[{"name":"Events","identifier":"events","value":[{"name":"Process","identifier":"process","checked":false},{"name":"System","identifier":"system","checked":false}]}]},{"name":"Trends","identifier":"chromatograms","checked":true,"value":[{"name":"TT","identifier":"Id_0","value":[{"identifier":"AI001","name":"AI001.Obj.Out_rCurrentValue","description":"External AI 01","checked":true},{"identifier":"AI002","name":"AI002.Obj.Out_rCurrentValue","description":"External AI 02","checked":true},{"identifier":"CSPR1","name":"CSPR1.Obj.Out_rCurrentValue","description":"Active Permeate CSPR","checked":true}]}]},{"name":"Event Summary","identifier":"eventSummary","checked":true}]', GETUTCDATE(), N'Bio4CAdmin', N'true', N'Approved', N'Bio4CAdmin', GETUTCDATE(), N'ec7c7ce3f5086b682459ce0c8d75530a4ec658e2ee4b99f0e231bf0558e9733da9c84643a19b18ad3c615f3fb7f4aa4b75ad6d16cde72a79afd0f72079401a1f', N'Bio4CAdmin', 1, N'RunSummary', N'CRS 50L', N'n')
GO
INSERT [dbo].[report_template] ([report_template_id], [report_template_name], [report_template_Json], [report_template_created_on], [report_template_created_by], [report_template_state], [report_template_status], [lastModifiedBy], [lastModifiedOn], [eSignatureCode], [approver], [signature_count], [template_type], [device_id], [is_default]) VALUES (10, N'testDraftTemplate', N'[{"name":"Run Header","identifier":"runHeader","checked":true,"disabled":true},{"name":"Pre Run Data","identifier":"preRunData","checked":true},{"name":"Audit Trail","identifier":"auditTrail","checked":true},{"name":"Run Summary","identifier":"runSummary","checked":false},{"name":"Alarms","identifier":"alarms","checked":false,"value":[{"name":"Events","identifier":"events","value":[{"name":"Process","identifier":"process","checked":false},{"name":"System","identifier":"system","checked":false}]}]},{"name":"Trends","identifier":"chromatograms","checked":false,"value":[]},{"name":"Event Summary","identifier":"eventSummary","checked":false}]', GETUTCDATE(), N'Bio4CAdmin', N'true', N'Draft', N'Bio4CAdmin', GETUTCDATE(), N'', N'', 1, N'RunSummary', N'CRS 50L', N'n')
GO
SET IDENTITY_INSERT [dbo].[report_template] OFF
GO
DELETE FROM [dbo].[report_repository]
GO
SET IDENTITY_INSERT [dbo].[report_repository] ON
GO
INSERT [dbo].[report_repository] ([report_id], [report_name], [created_by], [cause], [state], [status], [file_name], [template_id], [generation_executed_time], [template_version], [generation_triggered_time], [report_type], [esign_status], [signed_by], [signed_on], [esign_code], [drweb_url], [hetp_report_id]) VALUES (1, N'AuditTrail_1_Bio4CAdmin', N'Bio4CAdmin', N'manual', N'COMPLETED', N'SUCCESS', N'AuditTrail_1.pdf', NULL, GETUTCDATE(), N'', GETUTCDATE(), N'AuditTrail', N'Signed', N'Bio4CAdmin', GETUTCDATE(), N'43de7e13171d309d8cf13d151495980dbd779c5def672ff37a7a03c56f8a2f87277bdb59402adf991b03943b65d6321287a548db57ce4f2d12d78b5a1cff8688', N'http://localhost:4430/DRWeb/WebAPI/GenReport.aspx?report=Foundn_AuditTrail&format=pdf&reportTitle=%22Audit+Trail%22&StartDate=%222022-02-17+00%3A00%3A00%22&EndDate=%222022-02-17+23%3A59%3A59%22&userId=%22Bio4CAdmin%22&reportType=%22AuditTrail%22&fileName=%22AuditTrail_16%22&reportId=16&auditTrailUser=%22All%22&genTime=%2217%2FFeb%2F2022+04%3A27%3A41%22&timeZone=%22Central+Standard+Time%22&genTime=%2217%2FFeb%2F2022+10%3A27%3A41%22', NULL)
GO
INSERT [dbo].[report_repository] ([report_id], [report_name], [created_by], [cause], [state], [status], [file_name], [template_id], [generation_executed_time], [template_version], [generation_triggered_time], [report_type], [esign_status], [signed_by], [signed_on], [esign_code], [drweb_url], [hetp_report_id]) VALUES (18, N'RunSummary_18_Bio4CAdmin', N'Bio4CAdmin', N'manual', N'COMPLETED', N'SUCCESS', N'RunSummary_18_Bio4CAdmin.pdf', 1, GETUTCDATE(), N'', GETUTCDATE(), N'RunSummary', N'Signed', N'Bio4CAdmin', GETUTCDATE(), N'26eddeab805f8e094ff6f161c73613df219bc1adabc3897795e03a6e48b0a10fd44545386e047caa63e14976542db8b2b0c1f354e097b127deab1e4949c020b1', N'http://localhost:4430/DRWeb/WebAPI/GenReport.aspx?report=Foundn_RunSummary&format=pdf&reportTitle=%22Run+Summary%22&StartDate=%222022-02-17+05%3A27%3A37%22&EndDate=%222022-02-17+05%3A27%3A41%22&userId=%22Bio4CAdmin%22&reportType=%22RunSummary%22&fileName=%22RunSummary_18_Bio4CAdmin%22&reportId=18&templateName=%22testReportTemplate%22&offSetMins=0&deviceId=%22CRS+50L%22&HETPId=0&trendST=&trendET=&genTime=%2217%2FFeb%2F2022+07%3A20%3A03%22&timeZone=%22Central+Standard+Time%22&genTime=%2217%2FFeb%2F2022+13%3A20%3A03%22&userName=%22Administrator+Bio4C%22&signOn=%2217%2FFeb%2F2022+07%3A23%3A00%22', NULL)
GO
SET IDENTITY_INSERT [dbo].[report_repository] OFF
GO
