pipeline {
    tools {
        maven 'apache-maven-3.6.3'
        jdk 'java_11'
    }
	stages {
        stage('Initialize') {
			steps {
                script {
					rtMavenRun(
						tool: 'apache-maven-3.6.3', // Tool name from Jenkins configuration
						pom: 'pom.xml',
						goals: 'clean test,
						resolverId: "MAVEN_RESOLVER"
					)
				}
			}
		}
	}
}