pipeline {
    agent {
        label '!master'
    }
    tools {
        maven 'apache-maven-3.6.3'
        jdk 'java_11'
    }
	options {
        timestamps()
        buildDiscarder(logRotator(artifactNumToKeepStr: '5'))
    }
	stages {
        stage('Build & Test') {
			steps {
                script {
					rtMavenRun(
						tool: 'apache-maven-3.6.3', // Tool name from Jenkins configuration
						pom: 'pom.xml',
						goals: 'clean test',
						resolverId: "MAVEN_RESOLVER"
					)
				}
			}
		}
	}
}